# Generated by Django 3.1.4 on 2020-12-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(related_name='actors', to='core.Movie'),
        ),
    ]
