# Generated by Django 3.1.4 on 2020-12-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201224_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(related_name='actors', to='core.Movie'),
        ),
        migrations.AlterField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(related_name='characters', to='core.Movie'),
        ),
    ]
